Rephrased the section on tools used during pair programming
wmde/Hiring pull request #3
Opened 2021-03-18 10:13 UTC by manicki

2021-03-18 15:55 UTC, gbirke approved these changes

2021-03-22 08:45 UTC, jakobw requested changes

2021-03-22 08:45 UTC, jakobw commented on index.html
> +                            Studio Live Share, a service that allows synchronization of code between
```suggestion
                            Studio Live Share</a>, a service that allows synchronization of code between
```

2021-03-22 08:52 UTC, manicki commented on index.html
> +                            Studio Live Share, a service that allows synchronization of code between
thanks, huge HTML skills @manicki

2021-03-22 09:04 UTC, jakobw approved these changes

2021-03-22 09:05 UTC, merged